name: Docker Image CI

# when to run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:                # creates a button to execute from outside of repo
    inputs:
      image_version:
        description: 'Please specify a version'
        required: false
        default: "latest"
      tools_to_build:
        description: 'Please specify a tool'
        required: false
        default: "tool"        
     





jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tools/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tools:latest

  terraform-build:

    runs-on: ubuntu-latest
    if: github.event.inputs.tools_to_build == 'terraform'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./terraform/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/terraform:latest




